# Generated by Django 5.2.7 on 2025-12-04 00:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apepaterno', models.CharField(max_length=50)),
                ('apematerno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('domicilio', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id_alimentos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piezas', models.IntegerField(blank=True, null=True)),
                ('gramos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('contenido', models.TextField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.categoria')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.tipo')),
            ],
            options={
                'db_table': 'alimento',
            },
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id_accesorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcion', models.TextField()),
                ('contenido', models.TextField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.categoria')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.tipo')),
            ],
            options={
                'db_table': 'accesorio',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascotas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=50)),
                ('cuidados', models.TextField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.categoria')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.tipo')),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accesorio', models.ForeignKey(blank=True, db_column='id_accesorio', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.accesorio')),
                ('alimento', models.ForeignKey(blank=True, db_column='id_alimento', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.alimento')),
                ('mascota', models.ForeignKey(blank=True, db_column='id_mascota', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.mascota')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_mascotas.pedido')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.usuario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.pedido')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='app_mascotas.usuario')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
