# Generated by Django 5.2.7 on 2025-12-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='accesorios/', verbose_name='Imagen del Producto'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alimentos/', verbose_name='Imagen del Producto'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto de la Mascota'),
        ),
    ]
